name: Go

on:
  push:
    branches:
      - main
    paths:
      - "workbench/go"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "workbench/go"
      - ".github/workflows/go.yml"

jobs:
  lint:
    name: go-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workbench/go
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@3dfdce20f5ca12d264c214abb993dbb40834da90 # v2.7.2

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.workbench/go/.golangci.yml ./..."
          go_version_file: "./workbench/go/go.mod" # this should be relative to the root of the repository
          fail_level: "error"
          reporter: "github-pr-review"
          workdir: "./workbench/go"

  test:
    name: go-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./workbench/go
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./workbench/go/go.mod
          cache-dependency-path: ./workbench/go/go.sum
      - name: test
        run: go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v1
        with:
          config: ./.octocov.yml
          work-dir: "./workbench/go"
